DROP DATABASE a16henme;
CREATE DATABASE a16henme;
USE a16henme;
   
CREATE TABLE HMEDEL(
	HMEDELNAMN  VARCHAR(50),
	HMEDELNR    VARCHAR(15),
	BESKRIVNING	VARCHAR(100),
	PRIMARY KEY (HMEDELNAMN, HMEDELNR)
) 	ENGINE=INNODB;

CREATE TABLE AGENT(
	AGENT_NAMN	CHAR(1),	#Sid 6
    AGENT_NR	TINYINT(2),	#Sid 6
    LÖN			INTEGER,	#sid 7
    UNAMN		VARCHAR(10),
    CHECK       (AGENT_NAMN LIKE '[A-Z]'),
    CHECK		(AGENT_NR LIKE '[0-9][0-9]'),		#Behövs verkligen denna checken när datatypen är en tinyint?
    PRIMARY KEY (AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE DESINFO(
	AGENT_NAMN	CHAR(1),
    AGENT_NR	TINYINT(2),
    RATE		VARCHAR(10),
    SPECIALITET	VARCHAR(50),
    KAMPANJ		VARCHAR(50),
	PRIMARY KEY (AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES AGENT(AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE FÄLT(
	AGENT_NAMN	CHAR(1),
    AGENT_NR	TINYINT(2),
    KOMPETENS	VARCHAR(100),
	SPECIALITET	VARCHAR(100),
	RATE		VARCHAR(10),
	UPPDRAG		VARCHAR(100),
	PRIMARY KEY (AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES AGENT(AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE GRUPPLEDNING(
	AGENT_NAMN	CHAR(1),
    AGENT_NR	TINYINT(2),
    OPERATION	VARCHAR(100),
    RATE		VARCHAR(10),
    LYCKAD		VARCHAR(10),
	PRIMARY KEY (AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES AGENT(AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE HANDLEDNING(
	AGENT_NAMN	CHAR(1),
    AGENT_NR	TINYINT(2),
    OPERATION	VARCHAR(100),
    RATE		VARCHAR(10),
    LYCKAD		VARCHAR(10),
	PRIMARY KEY (AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES AGENT(AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE OPERATION(
	OPKODNAMNT	VARCHAR(50),
    OPSTDATUM	VARCHAR(10),
    SLDATUM		VARCHAR(10),
	SR			VARCHAR(10),
    AGENT_NAMN	VARCHAR(50),
    AGENT_NR	VARCHAR(50),
    PRIMARY KEY (OPKODNAMNT, OPSTDATUM),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES HANDLEDNING (AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE HMEDELOPERATION(
	HMEDELNAMN	VARCHAR(50),
	HMEDELNR    VARCHAR(15),
    OPKODNAMNT	VARCHAR(50),
    OPSTDATUM	VARCHAR(10),
    PRIMARY KEY (HMEDELNAMN, HMEDELNR, OPKODNAMNT, OPSTDATUM),
    FOREIGN KEY (HMEDELNAMN, HMEDELNR) REFERENCES HMEDEL (HMEDELNAMN, HMEDELNR),
    FOREIGN KEY (OPKODNAMNT, OPSTDATUM) REFERENCES OPERATION (OPKODNAMNT, OPSTDATUM)
) 	ENGINE=INNODB;

CREATE TABLE HMEDELFÄLT(
	HMEDELNAMN	VARCHAR(50),
    HMEDELNR	VARCHAR(50),
    AGENT_NAMN	VARCHAR(50),
	AGENT_NR	VARCHAR(15),
    PRIMARY KEY (HMEDELNAMN, HMEDELNR, AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (HMEDELNAMN, HMEDELNR) REFERENCES HMEDEL (HMEDELNAMN, HMEDELNR),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES FÄLT (AGENT_NAMN, AGENT_NR)
)	ENGINE=INNODB;

CREATE TABLE FÄLTOPERATION(
	AGENT_NAMN	VARCHAR(50),
    AGENT_NR	VARCHAR(15),
    OPKODNAMNT	VARCHAR(50),
    OPSTDATUM	VARCHAR(10),
    PRIMARY KEY (AGENT_NAMN, AGENT_NR, OPKODNAMNT, OPSTDATUM),
    FOREIGN KEY (AGENT_NAMN, AGENT_NR) REFERENCES FÄLT (AGENT_NAMN, AGENT_NR),
    FOREIGN KEY (OPKODNAMNT, OPSTDATUM) REFERENCES OPERATION (OPKODNAMNT, OPSTDATUM)
)	ENGINE=INNODB;

#Lägg till många till många tabeller
#Justera datatyper
#Lägg till constraints

insert into HMEDEL values ('Henrik', '7810165915', 'En riktig tuffing'); 

insert into AGENT values ('Marcus', '9104055919', '59500', 'Mackan');

select * from HMEDEL;

select * from AGENT;